### ISSUE TITLE
Dates are not parsed as Date

### ISSUE THREAD

**Issue by thomasheeney** [yxx4c/prisma-extension-redis#11]
Using Dates (e.g. Prisma type DateTime) will not be parsed correctly when using the cache. 

They are returned as strings instead of the Date object.

**Comment by yxx4c** [comment]
@thomasheeney,

Thank you for bringing this issue to my attention. Will investigate the problem and work on a solution as soon as possible.

**Comment by yxx4c** [comment]
Hello @thomasheeney ,

I wasn't able to replicate the results you mentioned. Could you please provide some examples and the steps to reproduce the issue? Thank you!

**Comment by yxx4c** [comment]
Hi @thomasheeney,

I was able to replicate the issue and found the root cause of it (which I was under the impression that prisma would handle by itself).

The problem stems from the default JavaScript implementation of `JSON.parse`, which does not support parsing value types beyond a few basic ones, including date. To address this, I can implement a fix using a reviver function. However, I plan to add an option in the `cache-config` (similar to the `auto-config`) that allows you to provide your own custom serialize and deserialize functions.

At that point, you can use `superjson.parse` in conjunction with `superjson.stringify`, which preserves the type information along with the JSON object, for an out-of-the-box experience.

**Comment by yxx4c** [comment]
Hi @thomasheeney,

The latest update v1.1.0 addresses this issue. Do check it out and let me know if anything. Happy caching!

**Comment by yxx4c** [comment]
Hi @thomasheeney,

I am marking this issue as completed, please let me know if you need anything.
